//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.14 at 08:16:16 PM MST 
//


package com.deltadental.mtv.sync.service;

import lombok.Data;

@Data
public class Timestamp {

    protected int nanos;

   }
